//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            //this.DocumentoViaje = new HashSet<DocumentoViaje>();
        }
    
        public string RUC { get; set; }
        public string Razon_Social { get; set; }
        public string Direccion { get; set; }
        public string Tipo { get; set; }
        public string DNI { get; set; }
    
        public virtual Persona Persona { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<DocumentoViaje> DocumentoViaje { get; set; }
    }
}
