//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using Prism.Mvvm;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente : BindableBase
    {
        private string ruc;

        [Required(ErrorMessage = "El campo RUC es obligatorio")]
        [StringLength(maximumLength: 20, MinimumLength = 6, ErrorMessage = "El RUC debe tener 10 digitos")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Solo números")]
        public string RUC
        {
            get { return ruc; }
            set { SetProperty(ref ruc, value); }
        }

        private string razon_Social;


        public string Razon_Social
        {
            get => razon_Social;
            set => SetProperty(ref razon_Social, value);
        }
        public string Direccion { get; set; }
        public string Tipo { get; set; }

        private string dni;
        public string DNI
        {
            get => dni;
            set
            {
                SetProperty(ref dni, value);
            }
        }

        private Persona persona;
        public virtual Persona Persona
        {
            get => persona;
            set
            {
                SetProperty(ref persona, value);
            }
        }

        public Cliente Clone()
        {
            return (Cliente)this.MemberwiseClone();
        }
    }
}
