//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoViaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentoViaje()
        {
            this.Viaje1 = new HashSet<Viaje>();
        }
    
        public int ID { get; set; }
        public string GRR { get; set; }
        public string GRT { get; set; }
        public string RUC { get; set; }
        public string Factura { get; set; }
        public string ID_Viaje { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Viaje Viaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viaje> Viaje1 { get; set; }
    }
}
