//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flete()
        {
            this.Viaje1 = new HashSet<Viaje>();
        }
    
        public int ID { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<double> Adelanto { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string ID_Viaje { get; set; }
    
        public virtual Viaje Viaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viaje> Viaje1 { get; set; }
    }
}
