//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viaje()
        {
            this.CuentasXRendir = new HashSet<CuentasXRendir>();
            this.DocumentoViaje = new HashSet<DocumentoViaje>();
            this.Flete = new HashSet<Flete>();
            this.Gasto = new HashSet<Gasto>();
            this.GastoV = new HashSet<GastoV>();
            this.Mercaderia = new HashSet<Mercaderia>();
            this.Resumen = new HashSet<Resumen>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Salida { get; set; }
        public string Lugar_Origen { get; set; }
        public Nullable<double> KM_Origen { get; set; }
        public Nullable<System.DateTime> Fecha_Llegada { get; set; }
        public string Lugar_Destino { get; set; }
        public Nullable<double> KM_Destino { get; set; }
        public string Nota { get; set; }
        public string Encargado { get; set; }
        public Nullable<int> ID_Documento { get; set; }
        public Nullable<int> ID_Mercaderia { get; set; }
        public Nullable<int> ID_Flete { get; set; }
        public Nullable<int> ID_Resumen { get; set; }
        public Nullable<int> ID_CuentasXRendir { get; set; }
        public string PlacaVehiculo { get; set; }
        public string DNI_Conductor { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasXRendir> CuentasXRendir { get; set; }
        public virtual CuentasXRendir CuentasXRendir1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoViaje> DocumentoViaje { get; set; }
        public virtual DocumentoViaje DocumentoViaje1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flete> Flete { get; set; }
        public virtual Flete Flete1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoV> GastoV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mercaderia> Mercaderia { get; set; }
        public virtual Mercaderia Mercaderia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resumen> Resumen { get; set; }
        public virtual Resumen Resumen1 { get; set; }
        public virtual Unidad_Vehicular Unidad_Vehicular { get; set; }
    }
}
